development: &development
  adapter: mysql2
  database: warboats_development
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  username: root
  reconnect: true
  socket: /var/run/mysqld/mysqld.sock
  innodb_large_prefix: true

test:
  <<: *development
  database: warboats_test
